version: "3"
services:
  serverless:
    container_name: serverless
    image: serverless
    build: .
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

    volumes:
      - ./src:/app/src
    tty: true
    stdin_open: true
