service: unitemate-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stackName: ${sls:stage}-${self:service}-stack
  deploymentBucket:
    name: juv-shun.sls-deployment-store
    maxPreviousDeploymentArtifacts: 3
  logRetentionInDays: 7
  apiGateway:
    apiKeys:
      - defaultKey-${sls:stage}
  iam:
    role:
      name: ${sls:stage}-${self:service}-role
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !GetAtt UnitemateMatchResultOriginTable.Arn
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - !GetAtt UnitemateAggregationResultBucket.Arn
            - !Join ["", [!GetAtt UnitemateAggregationResultBucket.Arn, "/*"]]
  environment:
    DYNAMODB_TABLE: !Ref UnitemateMatchResultOriginTable
    S3_BUCKET_NAME: !Ref UnitemateAggregationResultBucket

package:
  individually: true
  patterns:
    - "!**"
    - src/**
    - pyproject.toml
    - poetry.lock

functions:
  match_user_result:
    name: ${sls:stage}-${self:service}-user-result
    handler: src.match_api.handler.user_result
    events:
      - http:
          path: v1/match/user_result
          method: post
          private: true
  match_banned_api:
    name: ${sls:stage}-${self:service}-post-match-banned
    handler: src.match_api.handler.banned
    events:
      - http:
          path: match/banned
          method: post
          private: true

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements

custom:
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    UnitemateMatchResultOriginTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-unitemate-match-result-origin
        AttributeDefinitions:
          - AttributeName: namespace
            AttributeType: "S"
          - AttributeName: timestamp
            AttributeType: "N"
          - AttributeName: namespace_user_id
            AttributeType: "S"
        KeySchema:
          - AttributeName: namespace
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: namespace_user_id-timestamp-index
            KeySchema:
              - AttributeName: namespace_user_id
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UnitemateAggregationResultBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${sls:stage}-unitemate-match-result-aggregation
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
        LifecycleConfiguration:
          Rules:
            - Id: ArchivedRule
              Status: Enabled
              Transitions:
                - TransitionInDays: 90
                  StorageClass: DEEP_ARCHIVE
