service: unitemate-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stackName: ${sls:stage}-${self:service}-stack
  deploymentBucket:
    name: juv-shun.sls-deployment-store
    maxPreviousDeploymentArtifacts: 3
  logRetentionInDays: 7
  apiGateway:
    apiKeys:
      - defaultKey-${sls:stage}
  iam:
    role:
      name: ${sls:stage}-${self:service}-role
      statements:
        - Effect: Allow
          Action:
            - timestream:DescribeEndpoints
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - timestream:*
          Resource:
            - !GetAtt UnitemateTimeStreamDB.Arn
            - !Join ["", [!GetAtt UnitemateTimeStreamDB.Arn, "/*"]]
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - !GetAtt UnitemateCSVExportBucket.Arn
            - !Join ["", [!GetAtt UnitemateCSVExportBucket.Arn, "/*"]]
  environment:
    TIMESTREAM_DB_NAME: !Ref UnitemateTimeStreamDB
    USER_RESULT_TABLE: row_user_results-${sls:stage} # !GetAtt UnitemateTimeStreamUserResultTable.Name
    BASIC_RESULT_TABLE: row_basic_results-${sls:stage} # !GetAtt UnitemateTimeStreamUserResultTable.Name
    POKEMON_AGGREGATION_TABLE: pokemon-aggregation-${sls:stage} # !GetAtt UnitemateTimeStreamAggregationTable

package:
  individually: true
  patterns:
    - "!**"
    - src/**
    - pyproject.toml
    - poetry.lock

functions:
  match_user_result:
    name: ${sls:stage}-${self:service}-user-result
    handler: src.match_api.handler.user_result
    events:
      - http:
          path: v1/match/user_result
          method: post
          private: true
  match_basic_result:
    name: ${sls:stage}-${self:service}-basic-result
    handler: src.match_api.handler.basic_result
    events:
      - http:
          path: v1/match/basic_result
          method: post
          private: true
  csv_export_origin:
    name: ${sls:stage}-${self:service}-csv-export-origin
    handler: src.csv_export.handler.origin
    environment:
      EXPORT_BUCKET: !Ref UnitemateCSVExportBucket
    events:
      - schedule:
          name: ${self:service}-export-time-${sls:stage}
          description: Night Export Batch Event for ${self:service}
          rate: cron(0 1 * * ? *)

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements

custom:
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    UnitemateTimeStreamDB:
      Type: AWS::Timestream::Database
      Properties:
        DatabaseName: unitemate-${sls:stage}
    UnitemateTimeStreamUserResultTable:
      Type: AWS::Timestream::Table
      Properties:
        DatabaseName: !Ref UnitemateTimeStreamDB
        TableName: row_user_results-${sls:stage}
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: "1"
          MagneticStoreRetentionPeriodInDays: ${param:magetic_store_retention_period_in_days}
        MagneticStoreWriteProperties:
          EnableMagneticStoreWrites: true
          MagneticStoreRejectedDataLocation: {}
    UnitemateTimeStreamBaseResultTable:
      Type: AWS::Timestream::Table
      Properties:
        DatabaseName: !Ref UnitemateTimeStreamDB
        TableName: row_basic_results-${sls:stage}
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: "1"
          MagneticStoreRetentionPeriodInDays: ${param:magetic_store_retention_period_in_days}
        MagneticStoreWriteProperties:
          EnableMagneticStoreWrites: true
          MagneticStoreRejectedDataLocation: {}
    UnitemateTimeStreamAggregationTable:
      Type: AWS::Timestream::Table
      Properties:
        DatabaseName: !Ref UnitemateTimeStreamDB
        TableName: pokemon-aggregation-${sls:stage}
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: "1"
          MagneticStoreRetentionPeriodInDays: ${param:magetic_store_retention_period_in_days}
        MagneticStoreWriteProperties:
          EnableMagneticStoreWrites: true
          MagneticStoreRejectedDataLocation: {}
    UnitemateCSVExportBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-export-files-${sls:stage}
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
        LifecycleConfiguration:
          Rules:
            - Id: ExpirationRule
              Status: Enabled
              ExpirationInDays: 90
    UnitemateSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-scheduled-query-topic

params:
  prd:
    magetic_store_retention_period_in_days: "90"
  dev:
    magetic_store_retention_period_in_days: "2"
