service: unitemate-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stackName: ${sls:stage}-${self:service}-stack
  deploymentBucket:
    name: juv-shun.sls-deployment-store
    maxPreviousDeploymentArtifacts: 3
  logRetentionInDays: 7
  apiGateway:
    apiKeys:
      - defaultKey-${sls:stage}
  iam:
    role:
      name: ${sls:stage}-${self:service}-role
      statements:
        - Effect: Allow
          Action:
            - timestream:DescribeEndpoints
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - timestream:*
          Resource:
            - !GetAtt UnitemateTimeStreamDB.Arn
            - !Join ["", [!GetAtt UnitemateTimeStreamDB.Arn, "/*"]]
  environment:
    TIMESTREAM_DB_NAME: !Ref UnitemateTimeStreamDB
    USER_RESULT_TABLE: row_user_results-${sls:stage} # !GetAtt UnitemateTimeStreamUserResultTable.Name
    BASIC_RESULT_TABLE: row_basic_results-${sls:stage} # !GetAtt UnitemateTimeStreamUserResultTable.Name

package:
  individually: true
  patterns:
    - "!**"
    - src/**
    - pyproject.toml
    - poetry.lock

functions:
  match_user_result:
    name: ${sls:stage}-${self:service}-user-result
    handler: src.match_api.handler.user_result
    events:
      - http:
          path: v1/match/user_result
          method: post
          private: true
  match_basic_result:
    name: ${sls:stage}-${self:service}-basic-result
    handler: src.match_api.handler.basic_result
    events:
      - http:
          path: v1/match/basic_result
          method: post
          private: true

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements

custom:
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    UnitemateTimeStreamDB:
      Type: AWS::Timestream::Database
      Properties:
        DatabaseName: unitemate-${sls:stage}
    UnitemateTimeStreamUserResultTable:
      Type: AWS::Timestream::Table
      Properties:
        DatabaseName: !Ref UnitemateTimeStreamDB
        TableName: row_user_results-${sls:stage}
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: "1"
          MagneticStoreRetentionPeriodInDays: "90"
        MagneticStoreWriteProperties:
          EnableMagneticStoreWrites: true
          MagneticStoreRejectedDataLocation: {}
    UnitemateTimeStreamBaseResultTable:
      Type: AWS::Timestream::Table
      Properties:
        DatabaseName: !Ref UnitemateTimeStreamDB
        TableName: row_basic_results-${sls:stage}
        RetentionProperties:
          MemoryStoreRetentionPeriodInHours: "1"
          MagneticStoreRetentionPeriodInDays: "90"
        MagneticStoreWriteProperties:
          EnableMagneticStoreWrites: true
          MagneticStoreRejectedDataLocation: {}
